### ISSUE TITLE
need terse high level config file for specifying a whole system 

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/deployed-systems#1]

**Comment by rvosa** [comment]
How about a puppet manifest?

**Comment by jar398** [comment]
Ansible looks better (simpler, more lightweight) to me, but I haven't done
a serious review.

The main question here is whether to layer something on top of the current
ad hoc deployment system, or replace the current system.  If the vote is to
replace, we have to make sure that the chosen framework can handle all of
the peculiar operations we need - installs using apt-get, pip, and random
downloads; editing neo4j and apache configuration files; stopping and
starting neo4j; java 7/8 flexibility; etc.

**Comment by jar398** [comment]
@mtholder, can you sketch out what you have in mind, and how it would help?  Do you mean combining the 'api' and 'tree' config files into one file, or making a third file that points to them, or something deeper, like a more general way to bind services to hosts?

**Comment by mtholder** [comment]
I'm going to close this. I'm interpreting @rvosa 's latest comment on the:
   https://groups.google.com/forum/?fromgroups&hl=en#!topic/opentreeoflife-software/gWKW6GyLWOc
thread as an indication that that thread is the better place to discuss moving to a different deployment system.

@jar this issue was started when I was contemplating a terser system. See: https://github.com/OpenTreeOfLife/deployed-systems/blob/d063902130e54f186f0b2c68fe75936405ae1d17/terse.conf

I had a script that generated the full conf from something like that short version. Basically it filled in the stuff that does not change when we change branches. If memory serves, @jimallman  and I thought that it was worth considering but you weren't wild about it. Not a big deal, so I forgot about it. I should have closed this then.
